FROM microsoft/windowsservercore as root
LABEL maintainer="muller.john@gmail.com"

ENV erlang_download_url="http://erlang.org/download/otp_win64_18.0.exe" \
    ERLANG_HOME=c:\\erlang

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ADD erlang_install.exe c:\\erlang_install.exe

# download and install erlang using silent install option, and remove installer when done
RUN Start-Process -Wait -FilePath .\erlang_install.exe -ArgumentList /S, /D=$env:ERLANG_HOME ; \
    Remove-Item -Force erlang_install.exe


#Invoke-WebRequest -Uri $env:erlang_download_url -OutFile erlang_install.exe ; \

FROM microsoft/nanoserver
LABEL maintainer="muller.john@gmail.com"

ENV ERLANG_HOME=c:\\erlang
COPY --from=root c:\\erlang c:\\erlang

COPY --from=root C:\\windows\\system32\\msvcp100.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\msvcr100.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\vcomp100.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\gdi32.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\user32.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\comdlg32.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\win32u.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\msimg32.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\winsta.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\kernel32.dll C:\\windows\\system32


