FROM microsoft/windowsservercore:1709 as root
LABEL maintainer="muller.john@gmail.com"

ENV erlang_download_url="http://erlang.org/download/otp_win64_18.0.exe" \
    ERLANG_HOME=c:\\erlang

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# download and install erlang using silent install option, and remove installer when done
RUN Invoke-WebRequest -Uri $env:erlang_download_url -OutFile erlang_install.exe ; \
    Start-Process -Wait -FilePath .\erlang_install.exe -ArgumentList /S, /D=$env:ERLANG_HOME ; \
    Remove-Item -Force erlang_install.exe


FROM microsoft/nanoserver:1709
LABEL maintainer="muller.john@gmail.com"

ENV ERLANG_HOME=c:\\erlang
COPY --from=root c:\\erlang c:\\erlang
COPY .erlang.cookie c:\\windows

RUN icacls c:\windows\.erlang.cookie /grant %USERNAME%:F

COPY --from=root C:\\windows\\system32\\msvcp100.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\msvcr100.dll C:\\windows\\system32
COPY --from=root C:\\windows\\system32\\vcomp100.dll C:\\windows\\system32